kind: pipeline
name: default

steps:
- name: OSQ
  image: python:3
  commands:
  - apt update
  - apt install -y git
  - git submodule update --init --recursive
  - pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - qio platform install https://github.com/OS-Q/P117/archive/master.zip
  - qio run -d tests/external-libs
  - qio run -d tests/internal-libs
