name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  UPLOAD_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        examples:
          - "tests/external-libs"
          - "tests/internal-libs"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1
    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
        qio update
        qio platform install https://github.com/OS-Q/P117/releases/latest/download/P117.zip

    - name: Build
      if: github.repository == 'OS-Q/A117'
      run: |
        qio run -d ${{ matrix.examples }}

  release:
    needs:
      - build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=release_tag::release_a12_$(date +"%Y.%m.%d")_${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=status::success"

      - name: Package Src
        id: package
        run: |
          echo "Arduino Core A117 for LGT8F MCU" >> README.txt
          echo $(date +"%Y.%m.%d") >> README.txt
          echo ${GITHUB_REF/refs\/tags\//} >> README.txt
          echo -e "www.OS-Q.com\n" >> README.txt
          # git log --stat -1 >> README.txt
          zip -r A117.zip bootloaders cores libraries variants boards.txt platform.txt programmers.txt
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload Output
        if: steps.package.outputs.status == 'success' &&  env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: A117
          path: ${{ env.FIRMWARE }}/A117.zip

      - name: SHA-256
        id: SHA
        run: |
          ls -l ${{ env.FIRMWARE }}/A117.zip >> README.txt
          sha256sum  ${{ env.FIRMWARE }}/A117.zip >> README.txt
          # python -c "import json; import os; fp=open(os.path.expanduser('./a12_index.json'), 'r+'); data=json.load(fp); data['packages']['platforms']['size'] = '615499'; fp.seek(0); fp.truncate(); json.dump(data, fp); fp.close()"
          echo "::set-output name=status::success"

      - name: Upload Release
        id: upload-release
        uses: stopstopstop/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ env.FIRMWARE }}/A117.zip
            ${{ env.FIRMWARE }}/a12_index.json

      - name: get latest
        run: |
          wget https://github.com/OS-Q/A117/releases/latest/download/A117.zip -O TEST.zip

      - name: Delet new tag
        id: delet
        if: failure()
        run: |
          git fetch
          git tag -d ${{ steps.tag.outputs.release_tag }}
          git push origin :refs/tags/${{ steps.tag.outputs.release_tag }}

      - name: Setup OSS
        uses: stopstopstop/ossutil-action@master
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Upload To OSS
        id: OSS
        run: |
          rm A117.zip
          mkdir A117
          cp -r bootloaders cores libraries variants boards.txt platform.txt programmers.txt A117/
          zip -r A117.zip A117
          ls -l  ${{ env.FIRMWARE }}/A117.zip
          sha256sum  ${{ env.FIRMWARE }}/A117.zip
          ossutil cp ${{ env.FIRMWARE }}/A117.zip ${{ secrets.OSS_A_BUCKET }} -rf
          ossutil cp ${{ env.FIRMWARE }}/a12_index.json ${{ secrets.OSS_A_BUCKET }} -f
          echo "::set-output name=status::success"

      - name: Send Mail
        if: steps.rebuild.outputs.status == 'success' && !cancelled()
        uses: stopstopstop/mail-action@master
        with:
          server_address:  smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: OS-Q A117 Released
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{github.event.pusher.email}}
          content_type: text/html
          convert_markdown: true
          body: file://README.md
          attachments: a12_index.json , README.txt

      - name: notification
        uses: stopstopstop/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: ${{steps.rebuild.outputs.status}}

      - name: Delet mark tag
        run: |
          git fetch
          git tag -d ${GITHUB_REF/refs\/tags\//}
          git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}

  build_fail:
    needs:
      - build
    if: failure() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Delet tag
        id: delet
        run: |
          git fetch
          git tag -d ${GITHUB_REF/refs\/tags\//}
          git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}

  release_fail:
    needs:
      - release
    if: failure() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Delet tag
        id: delet
        run: |
          git fetch
          git tag -d ${GITHUB_REF/refs\/tags\//}
          git push origin :refs/tags/${GITHUB_REF/refs\/tags\//}
