name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'

env:
  UPLOAD_BUILD: true

jobs:
  check:
    name: check
    strategy:
      fail-fast: false
      matrix:
        examples:
          - "tests/external-libs"
          - "tests/internal-libs"
          - "libraries/E2PROM/examples"
          - "libraries/PMU/examples"
          - "libraries/WDT/examples"
          - "libraries/Wire/examples"
          - "libraries/LarduinoISP/examples"
          - "libraries/lgt328p/examples"
          - "libraries/Rtc_Pcf8563/examples"
          - "libraries/VUsbMouse/examples"
          - "libraries/differential_amplifier/examples"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install latest
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          qio platform install https://github.com/OS-Q/P12/releases/latest/download/P12.zip

      - name: Build
        id: build
        if: success() && github.repository == 'OS-Q/A12'
        run: |
          pio run -d ${{ matrix.examples }} > ${{ matrix.examples }}/log.txt

      - uses: actions/upload-artifact@v2
        if: failure() &&  env.UPLOAD_BUILD
        with:
          name: ${{ matrix.examples }}_${{ matrix.os }}
          path: ${{ matrix.examples }}
