name: nightly

on:
  schedule:
    - cron: '0 15 * * *'

jobs:
  build:
    name: QIO
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]
        examples:
          - "tests/external-libs"
          - "tests/internal-libs"
          - "libraries/E2PROM/examples"
          - "libraries/PMU/examples"
          - "libraries/WDT/examples"
          - "libraries/Wire/examples"
          - "libraries/LarduinoISP/examples"
          - "libraries/lgt328p/examples"
          - "libraries/Rtc_Pcf8563/examples"
          - "libraries/VUsbMouse/examples"
          - "libraries/differential_amplifier/examples"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          pio platform install https://github.com/OS-Q/P12/releases/latest/download/P12.zip

      - name: Build
        if: success()
        run: |
          pio run -d ${{ matrix.examples }}

  # platformio:
  #   name: PIO
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macos-latest]
  #       python: [3.7,3.9]
  #       example:
  #         - "tests/external-libs"
  #         - "tests/internal-libs"
  #         - "libraries/E2PROM/examples"
  #         - "libraries/PMU/examples"
  #         - "libraries/WDT/examples"
  #         - "libraries/Wire/examples"
  #         - "libraries/LarduinoISP/examples"
  #         - "libraries/lgt328p/examples"
  #         - "libraries/Rtc_Pcf8563/examples"
  #         - "libraries/VUsbMouse/examples"
  #         - "libraries/differential_amplifier/examples"

  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: "recursive"

  #     - name: Set up Python ${{ matrix.python }}
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: ${{ matrix.python }}

  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         repository: darkautism/pio-lgt8fx
  #         token: ${{ secrets.OSQ_REPO_TOKEN }}
  #         path: GH_Repo

  #     - name: Install dependencies
  #       working-directory: GH_Repo
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -U https://github.com/platformio/platformio/archive/develop.zip
  #         pio platform install file://.

  #     - name: Build examples
  #       working-directory: GH_Repo
  #       run: |
  #         pio run -d ${{ matrix.example }}
